### ISSUE TITLE
Nuget package .targets file creates Platform structure before source files

### ISSUE THREAD

**Issue by kevkov** [fabulous-dev/Fabulous.Avalonia#157]
The Fabulous.Avalonia nuget package (as of 2.0.0-pre10) contains the file `Fabulous.Avalonia.targets` which loads the `Platform` directory and file project items when the project is loaded. However,  it appears these are created before the source files are loaded. So for a new project created from the `fabulous-avalonia` template part of the structure is like this:
![image](https://github.com/fabulous-dev/Fabulous.Avalonia/assets/17431305/a9558d41-b772-4ad4-8f79-77df00732127)
The ordering of the items is wrong as some of the platform-specific files depend on `App.fs`.
![image](https://github.com/fabulous-dev/Fabulous.Avalonia/assets/17431305/7e3bc1a2-2f0d-4dc8-b9f8-4c423f5f5533)

In contrast, a project created from the xf-fsharp template in FSharp.Mobile.Templates has the equivalent of the .targets file inlined in the project fiile below the source files so the dependency order is correct.

Also, the samples in this project do something similiar with an `Import` of a targets file after the source files. However, I think the approach used by FSharp.Mobile.Templates is preferable as it easier for the user to change.

**Comment by edgarfgp** [comment]
@TimLariviere, any thoughts if we can achieve what you did `FSharp.Mobile.Templates` ?
