### ISSUE TITLE
`ISingleViewApplicationLifetime` is marked as NotClientImplementable by Avalonia

### ISSUE THREAD

**Issue by edgarfgp** [fabulous-dev/Fabulous.Avalonia#261]
We rely on implementing `ISingleViewApplicationLifetime` [see]( https://github.com/fabulous-dev/Fabulous.Avalonia/blob/24a52c38397db20bd088e47138a0825f87c072b9/src/Fabulous.Avalonia/AppBuilderExtensions.fs#L94C1-L106C47)  for the IOS view initialisation but it seems that we can not longer use this.

Error FS0366 : No implementation was given for those members:  'Controls.ApplicationLifetimes.ISingleViewApplicationLifetime.``(This interface or abstract class is -not- implementable by user code !)``() : unit' 'Controls.ApplicationLifetimes.IApplicationLifetime.``(This interface or abstract class is -not- implementable by user code !)``() : unit'Note that all interface members must be implemented and listed under an appropriate 'interface' declaration, e.g. 'interface ... with member ...'.

**Comment by edgarfgp** [comment]
Cc @TimLariviere any suggestion on how get around this limitation ?

**Comment by TimLariviere** [comment]
@edgarfgp What is enforcing this attribute? The compiler is throwing an error?
This is very annoying as this Avalonia `SingleViewApplicationLifetime` is marked internal and we cannot use the `Avalonia.iOS.AvaloniaAppDelegate` neither...

**Comment by edgarfgp** [comment]
@TimLariviere  yeah a compiler error FS0366 basically this interface is not longer implementable by user code

**Comment by TimLariviere** [comment]
We need to contact the Avalonia team to give us a workaround. I don't see another way for us currently

**Comment by edgarfgp** [comment]
Found a discussion about this issue https://github.com/AvaloniaUI/Avalonia/discussions/17275

**Comment by edgarfgp** [comment]
Resolved by  using `AvaloniaAppDelegate` for now.
