### ISSUE TITLE
Padding around the inner control and two selectable layers for each item.

### ISSUE THREAD

**Issue by edgarfgp** [fabulous-dev/Fabulous.Avalonia#77]
When items are added via the constructor (WidgetDataTemplate), it is not quite rendering correctly: 
- Padding around the inner control and two selectable layers for each item.
- It renders correctly when the controls are added as children.

![ListBox](https://user-images.githubusercontent.com/111297684/214368349-f2e64b15-c87f-4739-a654-49767dee938a.jpg)

_Originally posted by @ConradRoesch in https://github.com/fabulous-dev/Fabulous.Avalonia/issues/74#issuecomment-1402345409_

**Comment by edgarfgp** [comment]
@ConradRoesch Crated this issue to track this :) . Thanks for all the reports

**Comment by TimLariviere** [comment]
@edgarfgp maybe check how ListBoxItem is supposed to be used in Avalonia.
It's possible you don't need it when returning a TextBlock
