### ISSUE TITLE
Should the content param for the RadioButton builder be a builder for an IFabControl not an IFabRadioButton?

### ISSUE THREAD

**Issue by kevkov** [fabulous-dev/Fabulous.Avalonia#78]
https://github.com/fabulous-dev/Fabulous.Avalonia/blob/da54a0107d09a2a4a3221265d407ed6054e40dcf/src/Fabulous.Avalonia/Widgets/Controls/RadioButton.fs#L32

**Comment by edgarfgp** [comment]
@kevkov Yes good spot. I will happy accept a PR for that :)
